### ISSUE TITLE
Use Softplus in place of pure baseline for Mish. 

### ISSUE THREAD

**Issue by digantamisra98** [hunglc007/tensorflow-yolov4-tflite#1]
Hi. 
Noticing your implementation of Mish, I would suggest to use Softplus implementation instead of writing the inner function to be log(1+exp(x)). 
Softplus provides a threshold which is much more stable and avoids gradient overflow.

**Comment by jzoker** [comment]
Hi @digantamisra98.  Thanks for your suggesstion.
We used custom function because tflite didnt support Softplus yet. Going to add the option for training by Softplus with a threshold.
