### ISSUE TITLE
failed to read all data

### ISSUE THREAD

**Issue by bgamini** [hunglc007/tensorflow-yolov4-tflite#10]
Hi
I get 'failed to read all data' error in utlis.py, line 122:
`assert len(wf.read()) == 0, 'failed to read all data'`
In my case, len(wf.read()) equals 257717640 (257 MB) and it seems ok, why it should be 0?

**Comment by hunglc007** [comment]
@bgamini 
What model do you use ?
What pretrained weight do you use ?

**Comment by bgamini** [comment]
I downloaded weights from AlexeyAB's repository, from this link:
https://github.com/AlexeyAB/darknet/releases/download/darknet_yolo_v3_optimal/yolov4.weights

**Comment by hunglc007** [comment]
You can try this command
` detect.py --weights ./data/yolov4.weights --framework tf --model yolov4 --size 608 --image your_image_path`

**Comment by zcdliuwei** [comment]
Hi,
I also get 'failed to read all data' error when I follow your tutorial exactly:
assert len(wf.read()) == 0, 'failed to read all data'
when I tun the evaluate.py like blow: 
python evaluate.py --weights ./data/yolov4.weights 
I wonder where I'm wrong

**Comment by hunglc007** [comment]
You can pass —model yolov4, because default is yolov3

**Comment by zcdliuwei** [comment]
> You can pass —model yolov4, because default is yolov3

Yes, the problem has been solved. The model can work normally. Your work is amazing. I am a beginner of computer vision. I will study your code carefully in the next few days and train yolov4 on my own dataset，thanks

**Comment by bgamini** [comment]
> You can pass —model yolov4, because default is yolov3

I'm so sorry, In my case, YOLO.CLASSES value was wrong. I changed it and problem solved.
But another error occurred:
`InvalidArgumentError:  Input to reshape is a tensor with 1472880 values, but the requested shape has 103968`
I solved it too, by adding cv2.resize after cv2.imread in detect.py.
