### ISSUE TITLE
Unexpected results with Tiny YOLOv3

### ISSUE THREAD

**Issue by favre49** [hunglc007/tensorflow-yolov4-tflite#104]
After training for vehicle detection on a custom dataset on Darknet, I used those weights here. However, the results are not as expected. The difference can be seen [here](https://imgur.com/a/Cp4oESU).

My assumption is it could be an issue of the config file - for instance, I am not sure how the anchor masks are applied (as in Darknet) and I'm not sure what the stride parameter means here, since in darknet we can set them by the layer. Any help is appreciated.

**Comment by hunglc007** [comment]
Yolo-tiny is updated
