### ISSUE TITLE
Supporting Yolov4-tiny

### ISSUE THREAD

**Issue by yadav-sumit** [hunglc007/tensorflow-yolov4-tflite#11]
Thank you @hunglc007  for this helpful repo, can you share how to use yolov4-tiny, if it's not supported are you planning to support it in near time..

**Comment by jzoker** [comment]
Hi @yadav-sumit. Tiny version is not official supported on Yolov4 yet. We'll support it when it become available.

**Comment by hunglc007** [comment]
@yadav-sumit yolov3-tiny is supported. u can pass —tiny —weight yolov3-tiny.weights to use
