### ISSUE TITLE
intersect-gt-and-pred.py

### ISSUE THREAD

**Issue by zcdliuwei** [hunglc007/tensorflow-yolov4-tflite#12]
Hi,
I follow your tutorial exactly, and when I run the main.py in mAP folder like below:
python main.py --output results_yolov4_tf，
I get: 
Error. File not found: predicted/20.txt
You can avoid this error message by running extra/intersect-gt-and-pred.py

but there is no intersect-gt-and-pred.py file in extra.
 
I wonder where I'm wrong

**Comment by hunglc007** [comment]
@zcdliuwei i updated intersect-gt-and-pred.py in extra folder. u can pull newest code

**Comment by zcdliuwei** [comment]
> @zcdliuwei i updated intersect-gt-and-pred.py in extra folder. u can pull newest code

Amazing ！！
