### ISSUE TITLE
cannot reshape array of size 770091 into shape (256,384,3,3)

### ISSUE THREAD

**Issue by Lynchez** [hunglc007/tensorflow-yolov4-tflite#121]
File "save_model.py", line 56, in main
    save_tf()
  File "save_model.py", line 51, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "/home/nurettin/Documents/tensorflow-yolov4-tflite-master/core/utils.py", line 50, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 770091 into shape (256,384,3,3)

ı cant convert trained yolov4-tiny model in any converter

**Comment by seanjin97** [comment]
Facing this same issue too for "save_model.py"

**Comment by molimat** [comment]
If you open yolov4.py inside core folder you will see that the tiny version of yolov4 is still not created.

**Comment by hunglc007** [comment]
@Lynchez  Have you tried to pull newest code ?

**Comment by Lynchez** [comment]
Yes I tried still same issue . I think problem is there in my tiny.cfg I use 2 class in my project and filters is going to be 21. 

[convolutional]
size=1
stride=1
pad=1
filters=21
activation=linear

[yolo]
mask = 1,2,3
anchors = 10,14,  23,27,  37,58,  81,82,  135,169,  344,319
classes=2
num=6

**Comment by hunglc007** [comment]
@Lynchez in ``core/config.py`` u can replace  ``__C.YOLO.CLASSES              = "./data/classes/coco.names"`` with your data.names file.

**Comment by Lynchez** [comment]
Thanks its worked .
