### ISSUE TITLE
cannot reshape array of size 4565322 into shape (1024,512,3,3)

### ISSUE THREAD

**Issue by MI-LA01** [hunglc007/tensorflow-yolov4-tflite#126]
Hello,

Just trained on the latest master branch of https://github.com/AlexeyAB/darknet a custom detector using yolov4 (input size 320). 

Now from a fresh docker container (tensorflow/tensorflow:2.3.0rc0-gpu-jupyter) I cloned this repo ; tried a basic :

```python3 save_model.py --weights /content/drive/models/darknet/backup/yolov4-hails_best.weights --output ./checkpoints/yolov4-320 --input_size 320 --model yolov4```

And get : 

```
 File "save_model.py", line 60, in <module>
    app.run(main)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/usr/local/lib/python3.6/dist-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 56, in main
    save_tf()
  File "save_model.py", line 51, in save_tf
    utils.load_weights(model, FLAGS.weights, FLAGS.model, FLAGS.tiny)
  File "/usr/src/app/tensorflow-yolov4-tflite/core/utils.py", line 63, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 4565322 into shape (1024,512,3,3)
```

Are you supporting the latest weights from yolov4 ?

**Comment by MI-LA01** [comment]
Found, 
If you are training a custom model with a number of class != 80, so to speak something different than the pre-trained weights ; you will have to create your own class file (class.names) under data and set this new file in the config.py file as during the model creation, the number of class is automatically deduces

**Comment by inSight-mk1** [comment]
Thx for the solution.

**Comment by Ashwin-Ramesh2607** [comment]
@MI-LA01 Hey, I am trying to convert my custom model as well. Your method has helped me, but I face another issue. This repo takes an input shape of 416 or 608 and constructs the width and height of the input size as 416*416 or 608*608. However, the model I trained is on 832*608. Can you suggest me on next steps?

**Comment by MI-LA01** [comment]
Hi @Ashwin-Ramesh2607 : Did you checkout the latest version of this repository ? There was a fresh update on yesterday on save_model.py allowing to specify the input size of the model.

**Comment by Ashwin-Ramesh2607** [comment]
@MI-LA01 They allow us to specify the input size of the model, you are correct. But they take in a size of lets say, 608, and use the same value for width and height of the input size. I am not sure how to change it.

In line 19 of saved_model.py
`  input_layer = tf.keras.layers.Input([FLAGS.input_size, FLAGS.input_size, 3])`
I can change this to accept different value of width and height

In line 46, I can change it as well
```
boxes, pred_conf = filter_boxes(pred_bbox, pred_prob, score_threshold=FLAGS.score_thres, input_shape=tf.constant([FLAGS.input_size, FLAGS.input_size]))
```

However, how can I change the size here, my dimensions are 832*608, so which value must I use here?
```
output_tensors = decode(fm, FLAGS.input_size // 16, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
```
They have used FLAGS.input_size which is just a single value, not an array of 2 values. If the size is 608*608, no issues, we can plug 608 into each function call. But for 832*608, how do I proceed?

**Comment by zhubinsheng** [comment]
> @ MI-LA01他们允许我们指定模型的输入大小，您是正确的。但是它们的大小可以说是608，并且对输入大小的宽度和高度使用相同的值。我不确定如何更改它。
> 
> 在save_model.py的第19行中，
> ` input_layer = tf.keras.layers.Input([FLAGS.input_size, FLAGS.input_size, 3])`
> 我可以将其更改为接受不同的width和height值
> 
> 在第46行中，我也可以更改它
> 
> ```
> boxes, pred_conf = filter_boxes(pred_bbox, pred_prob, score_threshold=FLAGS.score_thres, input_shape=tf.constant([FLAGS.input_size, FLAGS.input_size]))
> ```
> 
> 但是，如何在这里更改尺寸，我的尺寸是832 * 608，所以在这里必须使用哪个值？
> 
> ```
> output_tensors = decode(fm, FLAGS.input_size // 16, NUM_CLASS, STRIDES, ANCHORS, i, XYSCALE, FLAGS.framework)
> ```
> 
> 他们使用了FLAGS.input_size，它只是一个值，而不是2个值的数组。如果大小为608 * 608，则没有问题，我们可以将608插入每个函数调用中。但是对于832 * 608，我该如何进行？

how to fix it? i also ==
