### ISSUE TITLE
Predict ok but wrong bboxes positioning 

### ISSUE THREAD

**Issue by MI-LA01** [hunglc007/tensorflow-yolov4-tflite#129]
As per the picture : 

![result](https://user-images.githubusercontent.com/197890/86534523-033d1b00-bed1-11ea-8937-a485bc09a7e1.png)

The model was trained with the original darknet and then converted. Config as follow : 
* A `3 classes`, 
* input is `[320,320,3]` ; 
* Anchors was recalculated before training using darknet binary and reported as well on the config.py `[14, 15, 19, 17, 22, 22, 36, 22, 26, 30, 38, 36, 32, 55, 55, 46, 73, 74]`
* Model is `YoloV4`. 
* It works using original `darknet detector test`

command used : 
```
!python detect.py --weights ./checkpoints/yolov4... --model yolov4 --size 320 --image /content/drive/.../20191223-094102-Ooooo-pass-1-region-2-12.jpeg
```

Any thought on that ?

**Comment by inSight-mk1** [comment]
I encountered thre same issue. 
The result with default input size 416 is normal. But it's has abnormal boxes position like you when using different input size (in my case, 608).

**Comment by inSight-mk1** [comment]
Solved. 
line 59 & 61 in detect.py, change this line to
boxes, pred_conf = filter_boxes(pred[1], pred[0], score_threshold=0.25, input_shape=(input_size, input_size))
Add your own input_size here, default is (416, 416)
@hunglc007

**Comment by dolortaste** [comment]
> Solved.
> line 59 & 61 in detect.py, change this line to
> `boxes, pred_conf = filter_boxes(pred[1], pred[0], score_threshold=0.25, input_shape=(input_size, input_size))`
> Add your own input_size here, default is (416, 416)
> @hunglc007

I'm not using tflite and still have this problem

**Comment by MI-LA01** [comment]
@inSight-mk1 : I tried to patch as you suggested but unfortunately still have the same issue.

**Comment by inSight-mk1** [comment]
> > Solved.
> > line 59 & 61 in detect.py, change this line to
> > `boxes, pred_conf = filter_boxes(pred[1], pred[0], score_threshold=0.25, input_shape=(input_size, input_size))`
> > Add your own input_size here, default is (416, 416)
> > @hunglc007
> 
> I'm not using tflite and still have this problem

Yes. The line I modified is in the tflite branch of the if-else clause.
You need to check where is wrong about the input size below the 'else:'
`        saved_model_loaded = tf.saved_model.load(FLAGS.weights, tags=[tag_constants.SERVING])
        infer = saved_model_loaded.signatures['serving_default']
        batch_data = tf.constant(images_data)
        pred_bbox = infer(batch_data)
        for key, value in pred_bbox.items():
            boxes = value[:, :, 0:4]
            pred_conf = value[:, :, 4:]`
The possible issue point is infer(batch_data). Unfortunately, I'm not familiar with tensorflow, so I cannot help you with this.

**Comment by inSight-mk1** [comment]
> @inSight-mk1 : I tried to patch as you suggested but unfortunately still have the same issue.

It seems the difference between our cases is anchors.

**Comment by hunglc007** [comment]
sr, because in ``save_model.py`` i set default ``input_shape = tf.constant([416,416])``. Pulling newest code to fix this issue

**Comment by MI-LA01** [comment]
@hunglc007 : The pb is somewhere else, your fix may help for tflite but not for the std yolov4 model trained from darknet/c implementation. 

I isolated and simplified on colab detect.py and replaced the function you used for drawing the boxes with the native ` tf.image.draw_bounding_boxes` and get the **same issue** : 
```
original_image = cv2.imread(image_path)
image_data = original_image / 255.
images_data = []

for i in range(1):
    images_data.append(image_data)
images_data = np.asarray(images_data).astype(np.float32)

batch_data = tf.constant(images_data)
pred_bbox = infer(batch_data)
for key, value in pred_bbox.items():
    boxes = value[:, :, 0:4]
    pred_conf = value[:, :, 4:]

boxes, scores, classes, valid_detections = tf.image.combined_non_max_suppression(
    boxes=tf.reshape(boxes, (tf.shape(boxes)[0], -1, 1, 4)),
    scores=tf.reshape(
        pred_conf, (tf.shape(pred_conf)[0], -1, tf.shape(pred_conf)[-1])),
    max_output_size_per_class=100,
    max_total_size=100,
    iou_threshold=iou,
    score_threshold=score
)

image_with_box = tf.image.draw_bounding_boxes(
    images_data, boxes, np.array([[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]]), name=None
)

plt.imshow(image_with_box[0]),plt.title("result")
plt.show()
```

Leading to have this : 
<img width="291" alt="Screen Shot 2020-07-06 at 11 20 30 AM" src="https://user-images.githubusercontent.com/197890/86583171-bca3fb00-bf7a-11ea-8150-0868c0d9bd56.png">

From this, I still really don't know where to look at.

**Comment by hunglc007** [comment]
> @hunglc007 : The pb is somewhere else, your fix may help for tflite but not for the std yolov4 model trained from darknet/c implementation.
> 
> I isolated and simplified on colab detect.py and replaced the function you used for drawing the boxes with the native ` tf.image.draw_bounding_boxes` and get the **same issue** :
> 
> ```
> original_image = cv2.imread(image_path)
> image_data = original_image / 255.
> images_data = []
> 
> for i in range(1):
>     images_data.append(image_data)
> images_data = np.asarray(images_data).astype(np.float32)
> 
> batch_data = tf.constant(images_data)
> pred_bbox = infer(batch_data)
> for key, value in pred_bbox.items():
>     boxes = value[:, :, 0:4]
>     pred_conf = value[:, :, 4:]
> 
> boxes, scores, classes, valid_detections = tf.image.combined_non_max_suppression(
>     boxes=tf.reshape(boxes, (tf.shape(boxes)[0], -1, 1, 4)),
>     scores=tf.reshape(
>         pred_conf, (tf.shape(pred_conf)[0], -1, tf.shape(pred_conf)[-1])),
>     max_output_size_per_class=100,
>     max_total_size=100,
>     iou_threshold=iou,
>     score_threshold=score
> )
> 
> image_with_box = tf.image.draw_bounding_boxes(
>     images_data, boxes, np.array([[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]]), name=None
> )
> 
> plt.imshow(image_with_box[0]),plt.title("result")
> plt.show()
> ```
> 
> Leading to have this :
> <img alt="Screen Shot 2020-07-06 at 11 20 30 AM" width="291" src="https://user-images.githubusercontent.com/197890/86583171-bca3fb00-bf7a-11ea-8150-0868c0d9bd56.png">
> 
> From this, I still really don't know where to look at.

Have you tried pulling newest code ? 
After that, run ``save_model.py`` again and try ``detect.py``. Remember adding ``--size``, which is your desirable size

**Comment by MI-LA01** [comment]
Oh, you meant re-saving the model.. 
Yes i confirm it works now. I did not realized in the new commit on `save_model.py` the : 

```
boxes, pred_conf = filter_boxes(pred_bbox, pred_prob, score_threshold=FLAGS.score_thres, input_shape=tf.constant([FLAGS.input_size, FLAGS.input_size]))
```
Great job though!
