### ISSUE TITLE
Training issue : NaN values

### ISSUE THREAD

**Issue by daiisuke27** [hunglc007/tensorflow-yolov4-tflite#135]
I am training YoloV4 on a custom dataset, and i'm always getting NaN as loss values after few steps of training. Any ideas ?

**Comment by daiisuke27** [comment]
Fixed by replacing mish activation with ReLu.

**Comment by XUYIRS** [comment]
Hello, I have encountered the same problem, can you tell me which mish activation did you replace with ReLU?
