### ISSUE TITLE
How to use trained weights ?

### ISSUE THREAD

**Issue by daiisuke27** [hunglc007/tensorflow-yolov4-tflite#136]
I trained yolov4 on a custom dataset.
I got four files as the output : 
![image](https://user-images.githubusercontent.com/58391484/86786442-4bd90d80-c064-11ea-9f9e-1a9a3c961f4b.png)
I tried detect.py with the weight file but it's not working ( i think because detect.py loads a model and all i have is weights )
Then i tried the save_model.py with those weights and had this error :
![image](https://user-images.githubusercontent.com/58391484/86786790-b0946800-c064-11ea-9cee-8f5faa66710d.png)

**Comment by seungyun-shin** [comment]
I faced same issue.. 

ValueError: cannot reshape array of size 4570707 into shape (1024,512,3,3)

any help.?

**Comment by daiisuke27** [comment]
> 
> 
> I faced same issue..
> 
> ValueError: cannot reshape array of size 4570707 into shape (1024,512,3,3)
> 
> any help.?

I fixed that issue by training my model first on darknet, then converting the weights to tensorflow. 
I guess the problem is that you are importing the pre-trained weights trained on COCO ( 80 classes ) and then training your own dataset with a different number of classes.
