### ISSUE TITLE
Error when converting weights trained on darknet

### ISSUE THREAD

**Issue by cjsflores** [hunglc007/tensorflow-yolov4-tflite#142]
I used save_model.py on the weights I trained using darknet itself.

I tried to debug the problem and I think it has something to do with the YOLO model used as a reference.
The number of layers is only 21 compared to the 27 on the yolov4-tiny implementation from the darknet github repo.

Also, when training using darknet, there's an option to change the size of the filters on the convolution layer before the yolo layer. Maybe that's why the ValueError when loading weights occurs
![tmp](https://user-images.githubusercontent.com/33479113/87246216-7c62e200-c47e-11ea-8163-ca56d4a989c7.PNG)

**Comment by alphapibeta** [comment]
@cjsflores 
Is it a custom model?
If yes then you will have to change the number of classes in 
```
path/tensorflow-yolov4-tflite/data/classes/coco.names

```
change according to the number of classes in your model while training

**Comment by cjsflores** [comment]
This solved my problem. Thank you
