### ISSUE TITLE
java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 10647, 4] and a Java object with shape [1, 52, 52, 3, 85].

### ISSUE THREAD

**Issue by tomkisiela** [hunglc007/tensorflow-yolov4-tflite#151]
Hello I tried to run yolov4-416 in the app but I got this error when I press the detect button on the Kite image.

**Comment by yar1k0v** [comment]
Any updates on this?

**Comment by tomkisiela** [comment]
Sorry I have no idea I think I'm going to rebuild an app from scratch.
Imo we need to tweak the app to accept the output of our model but I don't really know how to do this.

**Comment by gigilaw** [comment]
I have the exact issue, please let me know if anyone has managed to solve it!
