### ISSUE TITLE
[FunctionRequire] Hope to add some evaluation metrics in training process.

### ISSUE THREAD

**Issue by LiamTTT** [hunglc007/tensorflow-yolov4-tflite#153]
Hope developers can add some evaluation metrics like mAP, etc. 
BTW, The outputs form of different models(Pretrained yolov4, yolov4-tflite model or the yolov4 model in training) do not seem to be unified. It brings some trouble when modied for custom version.

**Comment by DanielFlash** [comment]
> Hope developers can add some evaluation metrics like mAP, etc.
> BTW, The outputs form of different models(Pretrained yolov4, yolov4-tflite model or the yolov4 model in training) do not seem to be unified. It brings some trouble when modied for custom version.

Hi! Did you manage to add metrics? I need to add metrics to save in tensorboard, but I totally do not understand how to add them. E.g., how to calculate mAP

**Comment by LiamTTT** [comment]
Sorry for taking so long to reply. I haven't been involved in related work for a long time.
