### ISSUE TITLE
How can I use the yolov4-tiny net

### ISSUE THREAD

**Issue by nanshenwei** [hunglc007/tensorflow-yolov4-tflite#177]
How can I use the yolov4-tiny net..
I tried to  train VOC with --tiny  , but there are much ERROR warning in the output, incluing "mismatched shape" etc...
Is it a unfinished version or the improper way I used 😢

**Comment by nanshenwei** [comment]
the reason is the code which in dataset.py has not been optimized for tiny. I finish the code now. Thinks.

**Comment by pskimdev** [comment]
Hi, @nanshenwei 
I converted the trained yolov4-tiny-3l.weights to ".pb" and ".tflite".
But there are no detection results in android. (In windows, there are detection results).
I really want to know how to optimize the"dataset.py" for tiny. I think that this file is the reason why I can't get results in android.
Could you please share your tips or code?
Thanks
