### ISSUE TITLE
YoloV4 FPS is lower 

### ISSUE THREAD

**Issue by reactivetype** [hunglc007/tensorflow-yolov4-tflite#19]
Why is FPS (frame per second) of YoloV4 FPS lower than Yolov3's?

**Comment by jinfagang** [comment]
@reactivetype Yolov4 is slower than yolov3, you probably want compare with original darknet's yolov4 speed.

**Comment by hunglc007** [comment]
yolov4 is slower than yolov3 with the same network resolution,
to get both AP and FPS improvement, use yolov4 with slightly lower network resolution
