### ISSUE TITLE
没有训练自己数据的步骤吗？

### ISSUE THREAD

**Issue by chunleiml** [hunglc007/tensorflow-yolov4-tflite#2]

**Comment by jzoker** [comment]
@chunleiml . Guess your question that is related to trainning code. It is being updated.

**Comment by chunleiml** [comment]
> @chunleiml . Guess your question that is related to trainning code. It is being updated soon.

Yes, I want to train my data，but I don't find any file like train.py，I'm looking forward to your masterpiece.

**Comment by jzoker** [comment]
@chunleiml it is updated
