### ISSUE TITLE
Files to apply delegate to dynamic sized tensors

### ISSUE THREAD

**Issue by josephbiko** [hunglc007/tensorflow-yolov4-tflite#203]
Hey, when trying to run my model(various versions) on mobile gpu/nnapi I get the following error, cpu works fine.

`     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
`.

Any ideas?

**Comment by josephbiko** [comment]
Happens when you run save_model without the --tflite flag., but still want to do tflite things...

**Comment by jaweii** [comment]
Im facing the same issue, how did you solved it?
