### ISSUE TITLE
convert_tflite.py crash on default dataset

### ISSUE THREAD

**Issue by rtrahms** [hunglc007/tensorflow-yolov4-tflite#21]
TF-gpu 2.1.0 + all required libraries
CUDA 10.1
Downloaded yolov4.weights from the link

Script command: 
python convert_tflite.py --weights ./data/yolov4.weights --output ./data/yolov4.tflite

Crash:
FileNotFoundError: [Errno 2] No such file or directory: '/media/user/Source/Data/coco_dataset/coco/5k.txt'

Looks like explicitly setting --quantize_mode works around this logic bug.

Thanks,
Rob

**Comment by hunglc007** [comment]
I have updated code to fix your issue

**Comment by abdalkhalik** [comment]
i have the same issue when i run:
**!python convert_tflite.py --weights yolov42.weights --output ./data/yolov4.tflite --quantize_mode full_int8**

however the error goes away if i removed '--quantize_mode full_int8' from above

**Comment by sterlingrpi** [comment]
> i have the same issue when i run:
> **!python convert_tflite.py --weights yolov42.weights --output ./data/yolov4.tflite --quantize_mode full_int8**
> 
> however the error goes away if i removed '--quantize_mode full_int8' from above
> 
> Edit:
> I just replaced **--quantize_mode full_int8** with **--quantize_mode int8** and it worked fine

full_int8 is very different from int8. Full_int8 quantizes the activations in addition to weights. It also requires a representative dataset, which can cause an error as the repo does not contain one and you must provide your own.

**Comment by abdalkhalik** [comment]
> > i have the same issue when i run:
> > **!python convert_tflite.py --weights yolov42.weights --output ./data/yolov4.tflite --quantize_mode full_int8**
> > however the error goes away if i removed '--quantize_mode full_int8' from above
> > Edit:
> > I just replaced **--quantize_mode full_int8** with **--quantize_mode int8** and it worked fine
> 
> full_int8 is very different from int8. Full_int8 quantizes the activations in addition to weights. It also requires a representative dataset, which can cause an error as the repo does not contain one and you must provide your own.

Thank you for the clarification
