### ISSUE TITLE
Question: How to convert yolo weights to *.pb using this framework?

### ISSUE THREAD

**Issue by rtrahms** [hunglc007/tensorflow-yolov4-tflite#22]
Thanks again for building this - very impressed with it!  Clean code too, well done!
I have used it successfully to convert some of our yolo weights files to tflite files, but haven't figured out how to convert yolo weights files to pb files.   Any advice here?
Rob

**Comment by paroque28** [comment]
Hi @rtrahms, let me know if you can do this

**Comment by paroque28** [comment]
Hi @rtrahms ,
I was able to export the frozen graph. See: https://github.com/paroque28/tensorflow-yolov4-tflite/commit/88f259c9f11d926f251f76ec182bbb7545f52ae3

However I am nopt sure it will work and have to test.
I also found this very helpful guide:
https://github.com/Tony607/keras-tf-pb/blob/master/keras_freeze_tf_pb.ipynb

**Comment by hunglc007** [comment]
i added save_model.py file to convert to .pb format

**Comment by yeu-github** [comment]
> i added save_model.py file to convert to .pb format

hi @hunglc007 ,
i couldnt find your file in your repositories, can you give a reference for it?
