### ISSUE TITLE
what shall i put in network size instead of 416 if my network size is 608x160

### ISSUE THREAD

**Issue by shubham-shahh** [hunglc007/tensorflow-yolov4-tflite#241]
what shall i put in network size instead of 416 if my network size is 608x160

**Comment by LC117** [comment]
Usually the trick is to paste the image on a square blank background. In your case you should paste on a 608x608 background. 
As 608/8=76 you should be fine with a size of 608.

**Comment by shubham-shahh** [comment]
Will try that @LC117

**Comment by hhk7734** [comment]
@shubham-shahh 
Hi~ Can you share your model?
I tested on [yolov4 module](https://wiki.loliot.net/docs/lang/python/libraries/yolov4/python-yolov4-about/).

**Comment by shubham-shahh** [comment]
Thanks, I'll check that module. @hhk7734

**Comment by shubham-shahh** [comment]
I finally did the inference with Darknet
