### ISSUE TITLE
if trying custom yolov4 training, only get result of yolov4.index and yolov4.data-00000-of-00001

### ISSUE THREAD

**Issue by KYUNGGUK-CHOI** [hunglc007/tensorflow-yolov4-tflite#244]
I have no idea how to do next to test on linux or deploy for android

**Comment by mathpopo** [comment]
@KYUNGGUK-CHOI   i have same issue, how can you do?

**Comment by KYUNGGUK-CHOI** [comment]
@mathpopo 
which one? linux or android?
after running custom train.py then run convert_tflite.py
you would get tflite file then adapt it on anroid

**Comment by vandics** [comment]
I got an error CUDA_ERROR_UNKNOWN: unknown error then Fatal Python error: Aborted when converting to tflite. Did you got this error too?
