### ISSUE TITLE
Android Library import error and Android app always crashing

### ISSUE THREAD

**Issue by FlavorDots** [hunglc007/tensorflow-yolov4-tflite#248]
![error](https://user-images.githubusercontent.com/58362241/96859316-efbfbb00-1493-11eb-80d8-d7dbd02d0056.PNG)

I am having problems with all the Tensorflow imports. It always says, "Cannot resolve symbol TFLiteObjectDetectionAPIModel", etc.

**Comment by nauyan** [comment]
@AlainMindana have you been able to resolve imports?

**Comment by FlavorDots** [comment]
@nauyan  Yes :)

**Comment by Kanatip-P** [comment]
> @nauyan Yes :)

how ? pls help me

**Comment by ibrandiay** [comment]
@AlainMindana  please help us ...
