### ISSUE TITLE
Running detect with tflite

### ISSUE THREAD

**Issue by parthjdoshi** [hunglc007/tensorflow-yolov4-tflite#289]
Hello. Thanks for the great repo. I had a query about running detect.py with the YOLOv4 model using the tflite framework.
While the core YOLOv4 file contains a decode_tflite function, why is it not called when running detect.py? How can the results of detect.py be directly passed to the filter_boxes function without postprocessing the output?

Once again, thank you for your help.

**Comment by zero90169** [comment]
There is a FLAG in decode function called FRAMEWORK, default setting is 'tf'. When we inference the tflite file the FRAMEWORK FLAG will be override into 'tflite' and the decode function will use decode_tflite function.

**Comment by parthjdoshi** [comment]
Oh yes. I missed that. Thank you :)
