### ISSUE TITLE
How can i convert YOLO v4 .weights to .pb  format

### ISSUE THREAD

**Issue by china56321** [hunglc007/tensorflow-yolov4-tflite#29]
How can i convert YOLO v4 .weights to .pb  format for tensorflow?

**Comment by hunglc007** [comment]
i added save_model.py file to convert to .pb format

**Comment by china56321** [comment]
> i added save_model.py file to convert to .pb format

something is wrong!
Traceback (most recent call last):
  File "save_model.py", line 4, in <module>
    from core.yolov3 import YOLOv4, YOLOv3, YOLOv3_tiny, decode
ModuleNotFoundError: No module named 'core.yolov3'

**Comment by china56321** [comment]
> i added save_model.py file to convert to .pb format

Have you tested the .pb format file ? Does it  work OK ?
