### ISSUE TITLE
convert_tflite.py

### ISSUE THREAD

**Issue by henbucuoshanghai** [hunglc007/tensorflow-yolov4-tflite#3]
when i get a ckpt or pb model of  tensorflow,i can use this convert_tflite.py???

**Comment by jzoker** [comment]
@henbucuoshanghai Yes you can use **TFLiteConverter.from_saved_model()** funtion in place of **TFLiteConverter.from_keras_model()** to load ckpt or pb models.

**Comment by henbucuoshanghai** [comment]
only  change this one function???to every tensorflow model??

**Comment by hunglc007** [comment]
@henbucuoshanghai it depends on your model, but most of current models can use this function

**Comment by henbucuoshanghai** [comment]
tensorflow model&nbsp; to tflite??????it is more easier than i think.
