### ISSUE TITLE
用自己的数据集训练得到了tensorflow的文件，怎么用？

### ISSUE THREAD

**Issue by Airyzf** [hunglc007/tensorflow-yolov4-tflite#30]
训练完得到四个文件：
checkpoint
yolov4.data-00000-of-00002
yolov4.data-00001-of-00002
yolov4.index

请问这几个文件怎么调用？

**Comment by ShihuaiXu** [comment]
怎么调用呀 楼主 请问你知道了吗 可以加我qq531232693细聊吗

**Comment by apupu1** [comment]
> 怎么调用呀 楼主 请问你知道了吗 可以加我qq531232693细聊吗


try: 
flags.DEFINE_string('weights', './checkpoints/yolov4', 'path to weights file')
model.load_weights(FLAGS.weights)
