### ISSUE TITLE
App keeps stopping galaxy S20

### ISSUE THREAD

**Issue by tesorrells** [hunglc007/tensorflow-yolov4-tflite#302]
I downloaded the repo and built an apk in android studio, ported it to my galaxy S20 but the app crashes after opening the camera or selecting detect. Is there a specific step I am missing?

**Comment by tesorrells** [comment]
Some more info:
![image](https://user-images.githubusercontent.com/15731791/105533299-effd6b80-5cb9-11eb-900e-94bcbc310085.png)

**Comment by bhimani07** [comment]
same here, is there any fix?
