### ISSUE TITLE
File "C:\Users\saran\Documents\Repositories\tensorflow-yolov4-tflite-master\core\utils.py", line 63, in load_weights     conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0]) ValueError: cannot reshape array of size 770091 into shape (256,384,3,3)

### ISSUE THREAD

**Issue by sarangtamrakar** [hunglc007/tensorflow-yolov4-tflite#326]
getting this error while converting yolov4 tiny model into .pb

**Comment by shitijkarsolia** [comment]
https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/147#issuecomment-742691380
https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/147#issuecomment-718817567

**Comment by sarangtamrakar** [comment]
I am able to resolved the proble by doing the changes in core/config file

**Comment by hibaalqaysi** [comment]
> I am able to resolved the proble by doing the changes in core/config file

Hi @sarangtamrakar , what changes you made to your config file, other than the path to custom.names?

**Comment by Pratyaksha-047** [comment]
> 

Hi, can you please what changes have you made to config file, other than path to classes.txt. I am using YoloV3 darknet model
