### ISSUE TITLE
detection problem after converting darknet to tensorflow

### ISSUE THREAD

**Issue by bqdong** [hunglc007/tensorflow-yolov4-tflite#330]
Hi, I use darknet to train my custom dataset. Then I convert weight file to tensorflow. When I try to detect, I get different result comparing to use darknet.
Here is darknet:
![image](https://user-images.githubusercontent.com/52027654/114526472-99c91480-9c79-11eb-9965-28c422424aef.png)
Tensorflow:
![image](https://user-images.githubusercontent.com/52027654/114526611-be24f100-9c79-11eb-8f53-4a70cf5a4063.png)
The boxes get bigger!
When I convert, I only modify [this line](https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/9f16748aa3f45ff240608da4bd9b1216a29127f5/core/config.py#L14).
Why?

**Comment by Micky-123** [comment]
@bqdong : were you able to root cause the above issue?

**Comment by bqdong** [comment]
@Micky-123 No way

**Comment by WenOOI** [comment]
I met the same problem like yours. Have you solved it?
I changed the 'width' and 'height' of 'cfg/yolov4-tiny-custom.cfg' from 416 to 320 in darknet, and then I correspondingly changed the size in 'save_modle.py' and 'detect.py' of Tensorflow. So I have made sure the size is the same. But the result shows the same problem presented above.
Hope someone can answer my question. Thanks!

**Comment by WenOOI** [comment]
https://github.com/hunglc007/tensorflow-yolov4-tflite/issues/174#issuecomment-666055130
I solved my problem according to this answer.

**Comment by bqdong** [comment]
@WenOOI The way you find should work. I use [opencv dnn module](https://docs.opencv.org/4.5.2/d6/d0f/group__dnn.html) to read darknet directly and it works well. This is also a way to solve this problem.
