### ISSUE TITLE
GPU usage

### ISSUE THREAD

**Issue by FreakieHuang** [hunglc007/tensorflow-yolov4-tflite#35]
Thx for your great work and sharing. 

I am currently using your code training AOC dataset. 

but the usage of gpu is quite low, always below 50% using single Titan Xp. 
1. Will you improve it? 
2. Will you add more backbone such as mobilenet? 
3. Will it support multi-gpus training? 

Many thx for your open-sourcing. 

best regards. 
顺颂业祺。

**Comment by jzoker** [comment]
you can use tensorrt, which is more optimal in gpu usage. the convert to tensorrt was already in readme
