### ISSUE TITLE
Yolov4-tiny-3l.cfg

### ISSUE THREAD

**Issue by Haerin0** [hunglc007/tensorflow-yolov4-tflite#353]
I trained my custom dataset with yolov4-custom.cfg, yolov4-tiny-custom.cfg and yolov4-tiny-3l.cfg.
it worked fine except yolov4-tiny-3l.cfg. it doesn't shows any bounding boxes at all. is that mean it can't detect anything? if so, which part of yolov4-tiny-3l.cfg should i edit? Thank you.

**Comment by aditya-5842** [comment]
I think yolov4-tiny-3l is not yet implemented in the repo. I have made the necessary for this one and it's is working for me.

Have a look at this: https://github.com/aditya-5842/tensorflow-yolov4-tflite OR you can look into  #325

**Comment by kaijaz123** [comment]
@aditya-5842 Hi good day. I am using your repo  https://github.com/aditya-5842/tensorflow-yolov4-tflite to convert the yolov4-tiny-3l weights. However, it detects nothing when I run the detectvideo. Did I need to change anything?

Command to convert:
`!python save_model.py --weights weights/yolov4-tiny-3l_best.weights --input_size 416 --tiny --model yolov4 --output checkpoints/3l_ball_416`

**Comment by aditya-5842** [comment]
@kaijaz123 There is a small change in the command that you are using.

`python save_model.py --weights ./data/yolov4-tiny-3l-608_5000.weights  --output ./checkpoints/yolov4-tiny-3l-608 --input_size 608 --model yolov4-tiny-3l --tiny`

Thank you for using my repo. If you will notice there is another branch in my repo, there I have these made change. You can find the above command and necessary changes in the ***yolov4-tiny-3l-fix*** branch.

If you're trained model predicts multiple classes, please make necessary changes here:

https://github.com/aditya-5842/tensorflow-yolov4-tflite/blob/yolov4-tiny-3l-fix/core/config.py#L14

**Comment by kaijaz123** [comment]
@aditya-5842 Hi, sorry for that. I didnt notice there was another branch as I was using the original code. It is working and able to detect now. Thanks man!
