### ISSUE TITLE
Test the .pb format file 

### ISSUE THREAD

**Issue by china56321** [hunglc007/tensorflow-yolov4-tflite#36]
@When i test the .pb format file using the following code:
with tf.Session() as sess:
    with tf.gfile.FastGFile("saved_model.pb",'rb') as  f:
        graph_def = tf.GraphDef()
        tf.Graph.as_graph_def()
        graph_def.ParseFromString(f.read())
        g_in=tf.import_graph_def(graph_def)
        LOGDIR='/log'
        train_writer=tf.summary.FileWriter(LOGDIR)
        train_writer.add_graph(sess.graph)
@It gives following error :
       File "testing.py", line 7, in <module>
      graph_def.ParseFromString(f.read())
      google.protobuf.message.DecodeError: Error parsing message
@How to solve this problem? Thanks

**Comment by lddsjy** [comment]
Try another way of getting a pb file and doing model inference. “saved_model.pb” doesn’t freeze graph. [https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py](url)

**Comment by china56321** [comment]
> Try another way of getting a pb file and doing model inference. “saved_model.pb” doesn’t freeze graph. [https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py](url)

Can this be used to generate .pb file for yolov4 weights  ?

**Comment by lddsjy** [comment]
It can convert ckpt into pb . Check the folder containing saved-model.py and you will find ckpt files in the variable folder in it

**Comment by china56321** [comment]
> It can convert ckpt into pb . Check the folder containing saved-model.py and you will find ckpt files in the variable folder in it

You mean this website "https://github.com/leimao/Frozen_Graph_TensorFlow/blob/master/TensorFlow_v2/train.py "
can convert ckpt into pb ?
Do you know how  to convert yolov4 weights to pb or ckpt ?
