### ISSUE TITLE
Multiple bounding boxes for the same object

### ISSUE THREAD

**Issue by OneManArmy93** [hunglc007/tensorflow-yolov4-tflite#360]
Hello, after I converted my Yolov4 to tflite version using the command `python convert_tflite.py --weights ./checkpoints/yolov4-608 --output ./checkpoints/yolov4-608-fp16.tflite --quantize_mode float16` and then running the script `detect.py` I get multiple bounding boxes for the same objet.
Please note that I have a custom dataset and therefore converted the custom weights.

**Comment by m-peker** [comment]
Hi,

I also faced the same problem. Did you find a solution?

**Comment by OneManArmy93** [comment]
@m-peker hello, after looking around in the code I managed to fix the multiple BB issue.
in the script `detect.py` you just have to change the value of the `iou` to 0.1 or any other value (you just have to experiment):
`flags.DEFINE_float('iou', 0.45, 'iou threshold')`  by `flags.DEFINE_float('iou', 0.1, 'iou threshold')`

**Comment by m-peker** [comment]
Thank you. Now, there is only one detection for each object.

**Comment by roderick1014** [comment]
Hi, is your output weight of training a ".data-00000-of-00001" & ".index" files? Then you transform them to ".pb" file and ".tflite" after that.
@OneManArmy93
