### ISSUE TITLE
convert_trt.py - FileNotFoundError for 'coco_dataset/coco/5k.txt' 

### ISSUE THREAD

**Issue by kaijaz123** [hunglc007/tensorflow-yolov4-tflite#373]
```
Script:
!python convert_trt.py --weights ./checkpoints/yolov4-tiny-ball.tf --quantize_mode int8 --output ./checkpoints/tiny-ball-416-trt-int8

Error:
FileNotFoundError: [Errno 2] No such file or directory: '/media/user/Source/Data/coco_dataset/coco/5k.txt'
```
When I try with quantize_mode float16 it works but crash on int8.

has anyone encountered this problem before while converting trt mode?

Thanks.

**Comment by abhi-84** [comment]
I am also facing same issue. have u resolved it?

**Comment by kaijaz123** [comment]
Unfortunately no. As the error stated, we need to find a way to get the txt file for the coco dataset.
