### ISSUE TITLE
Why is the training always out of 123800?

### ISSUE THREAD

**Issue by geekjr** [hunglc007/tensorflow-yolov4-tflite#377]
Why is the training always out of 123800, and is there a way to change that?

**Comment by ibrandiay** [comment]
what is your dataset size?

**Comment by geekjr** [comment]
Standard COCO dataset

**Comment by ibrandiay** [comment]
what is the 123800 ? the number of epochs?

**Comment by geekjr** [comment]
It's the # of steps.
