### ISSUE TITLE
weights array size does not match?

### ISSUE THREAD

**Issue by noprohuangqi** [hunglc007/tensorflow-yolov4-tflite#4]
when I try to convert , this error happens :

core/utis.py , line 114
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 4629942 into shape (1024,512,3,3)

thanks in advance!

**Comment by hunglc007** [comment]
What file do you run ?
What model do you use ? 
What pretrained weight do you use ?

**Comment by noprohuangqi** [comment]
my command is：
python convert_tflite.py --weights ./data/yolov4.weights --output ./data/yolov4.tflite

and I changed my own weights， this weights is trained on a dataset like voc ， but less labels ，and model settings are same as  yolov4 (608*608 input).

thanks!

**Comment by hunglc007** [comment]
@noprohuangqi can u post or email me your cfg file? i can check your isssue

**Comment by noprohuangqi** [comment]
of cource , can u give me a email , then I send this for you to check

**Comment by hunglc007** [comment]
@noprohuangqi  in core/yolov4.py line 89, 102 and 114 u change NUM_CLASS equal to your number classes of your dataset

**Comment by noprohuangqi** [comment]
ok  , I will try . And do I need change coco.names to voc.names?

**Comment by noprohuangqi** [comment]
thanks , finally success. Thank you for your help
