### ISSUE TITLE
Not working on Video

### ISSUE THREAD

**Issue by agoor97** [hunglc007/tensorflow-yolov4-tflite#409]
The Model is fine for Image, but for video and webcam, it doesn't work
There is an output but without boxes around objects.

**Comment by shsur-27** [comment]
hey @AGOOR97 did you found any solution because i also stuck in similar situation

**Comment by agoor97** [comment]
Yes, I did one 
Here is the Link
https://github.com/AGOOR97/Flask_API_object_detection_real_time
