### ISSUE TITLE
I really want to convert .weights into a .tflite model but nothing works

### ISSUE THREAD

**Issue by Vxtzq** [hunglc007/tensorflow-yolov4-tflite#478]
hello, i've trained a yolov4-tiny model with darknet, and I would like to convert it in tflite, I tried everything, but i get errors every times, or if no errors, the converted model do not work properly (weird boxes position with 0.90 accuarcy), if someone could convert the model for me or tell me a  solution, it would be really great, thank in advance for your help.
if you need more imformztion, feel free to ask.

**Comment by Vxtzq** [comment]
and also is windows better? because i'm using ubuntu linux

**Comment by kXborg** [comment]
Not working on colab. Something wrong with CUDA 12.

**Comment by Vxtzq** [comment]
Sorry for very late response I'm on a PC actually. I quite abandonned this project. I will try perhaps with a new PC and see if it works.
