### ISSUE TITLE
No module named 'core.utils'/No module named 'core.yolov4'

### ISSUE THREAD

**Issue by wadewangpower** [hunglc007/tensorflow-yolov4-tflite#5]
I try to run the scripts, but got errors as below:
![image](https://s1.ax1x.com/2020/04/28/JIIJns.png)

why the scripts cannot detect core.utils and core.yolov4, i have run the scripts under the parent folder 
![image](https://user-images.githubusercontent.com/43233772/80502608-7000da00-89a3-11ea-91a4-e1976aa9ea7f.png)

**Comment by jzoker** [comment]
@wadewangpower Seem like an python path error. It is seem that you have pycharm installed, can you run the file with pycharm?  Usually PYTHON PATH and VARIABLES are screw in window, so i recommend that you do not deal with it and move to ubuntu.

**Comment by wadewangpower** [comment]
> @wadewangpower Seem like an python path error. It is seem that you have pycharm installed, can you run the file with pycharm? Usually PYTHON PATH and VARIABLES are screw in Window, so i recommend that you should use Ubuntu instead.

Now,  after i git pull the latest code and rerun the command line, everything is OK ! I found, yesterday the second command line's weights path might be wrong, its suffix is **.tf** instead of **.weights**, you can check it from my screenshot above. so i think the error maybe come from this ~

**Comment by wadewangpower** [comment]
The output yolov4-int8.tflite is a little large, it is still not suitable to integrate in android app, hope the smaller but still precise tflite model can come up soon  ：）

**Comment by james94** [comment]
Check if **__init__.py** file exists in **core/** directory. Helped me run **save_model.py** from my Anaconda 3 Command Prompt on Windows.
