### ISSUE TITLE
Android is not function..

### ISSUE THREAD

**Issue by ubix12** [hunglc007/tensorflow-yolov4-tflite#57]
I made tflite and I have to build app through Android studio. Can you explain how to build?

I just got yolov4.tflite. I don't know what I have to do next step..

On android studio this error occrured

Error while executing: am start -n "org.tensorflow.lite.examples.detection/org.tensorflow.lite.examples.detection.MainActivity" -a android.intent.action.MAIN -c android.intent.category.LAUNCHER
Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] cmp=org.tensorflow.lite.examples.detection/.MainActivity }
Error type 3
Error: Activity class {org.tensorflow.lite.examples.detection/org.tensorflow.lite.examples.detection.MainActivity} does not exist.

Error while Launching activity

**Comment by EuphoriaCelestial** [comment]
I have successfully built the app after change sdk to 29 (android 10) to match with android version on my Pixel XL
Open project with Android Studio and follow its suggestions about SDK, NDK, gradle, ... it will save you a lot of time

**Comment by deepseek** [comment]
@EuphoriaCelestial were you able to inference at android? at what fps? device?

**Comment by ubix12** [comment]
I guess.. custom yolov4 is not working on this code. I made 4 class detector. but when i convert my custom yolov4 detector to tffile then it found another coco detector.. I dont know why this happened.

**Comment by EuphoriaCelestial** [comment]
> @EuphoriaCelestial were you able to inference at android? at what fps? device?

yes, the app not show fps, but it take very long time to detect and classify a frame. You must hold your phone still about 7 secs. I installed on Google Pixel XL

**Comment by EuphoriaCelestial** [comment]
> I guess.. custom yolov4 is not working on this code. I made 4 class detector. but when i convert my custom yolov4 detector to tffile then it found another coco detector.. I dont know why this happened.

how did you converted to tflite? there are many params need to be changed when convert

**Comment by ubix12** [comment]
> > I guess.. custom yolov4 is not working on this code. I made 4 class detector. but when i convert my custom yolov4 detector to tffile then it found another coco detector.. I dont know why this happened.
> 
> how did you converted to tflite? there are many params need to be changed when convert

I just change class number. This github is not suitable for custom model? Should I change another parameters?

**Comment by ubix12** [comment]
> > > > I guess.. custom yolov4 is not working on this code. I made 4 class detector. but when i convert my custom yolov4 detector to tffile then it found another coco detector.. I dont know why this happened.
> > > 
> > > 
> > > how did you converted to tflite? there are many params need to be changed when convert
> > 
> > 
> > I just change class number. This github is not suitable for custom model? Should I change another parameters?
> 
> It should be suitable. Have you take a look at those parameters?
> 
> `flags.DEFINE_string('weights', 'yolov4.weights', 'path to weights file')`
> `flags.DEFINE_string('output', 'yolov4.tflite', 'path to output')`
> `flags.DEFINE_boolean('tiny', False, 'path to output')`
> `flags.DEFINE_integer('input_size', 416, 'path to output')`
> `flags.DEFINE_string('model', 'yolov4', 'yolov3 or yolov4')`
> `flags.DEFINE_string('quantize_mode', "int8", 'quantize mode (int8, float16, full_int8)')`
> `flags.DEFINE_string('dataset', "/media/user/Source/Data/coco_dataset/coco/5k.txt", 'path to dataset')`

Oh. I got it. I think I didn't set dataset flag. Thanks. Should I enter --dataset ./data/dataset/yolov4.txt ?
