### ISSUE TITLE
Inference with serving model on CPU is too slow

### ISSUE THREAD

**Issue by lynx97** [hunglc007/tensorflow-yolov4-tflite#60]
I converted yolov4 weights to saved_model with input size = 512. When I inferenced, It took 0.9s in CPU (core i9 9900k)
The time for calling serving api is 0.3s. But function `postprocess_bbbox` in `core/utils.py` took 0.55s. I found the operation `np.tile` took much time (0.53s)
How to improve the the inference of YoloV4 on CPU?

**Comment by pshwetank** [comment]
Has this issue been resolved no @lynx97 ?

**Comment by lynx97** [comment]
> Has this issue been resolved no @lynx97 ?

In the post-processing function, you should not use both tensorflow and numpy library. That makes your performance too slow.

**Comment by pshwetank** [comment]
@lynx97 So you mean I must use either one of them to get optimal speed for inference?
