### ISSUE TITLE
Trying Quantization-Aware Training

### ISSUE THREAD

**Issue by ankandrew** [hunglc007/tensorflow-yolov4-tflite#62]
I see the actual INT8 quantization is done via post training quantization. Did you try doing the Quantization aware training from [model optimization](https://www.tensorflow.org/model_optimization/guide/quantization/training)? If so, were there good results?

**Comment by sterlingrpi** [comment]
If anyone could show me quant aware training working on any project I would be impressed. It was kind of like vapor-ware. We waited almost a year for it to come out. And then there was some research that showed post int quantization was just as good, and sometimes better in some cases. Then it kind of had a soft launch in nightly builds about a month ago. https://github.com/tensorflow/tensorflow/issues/27880#issuecomment-611079359

**Comment by aluds123** [comment]
@ankandrew @sterlingrpi 
I have tried quantization-aware training (but not on hunglc007/tensorflow-yolov4-tflite )
But I haven't put it on android.
