### ISSUE TITLE
Inference problems with pretrained yolov4.weights?

### ISSUE THREAD

**Issue by 2033329616** [hunglc007/tensorflow-yolov4-tflite#64]
When as run
`python detect.py --weights ./data/yolov4.weights --framework tf --size 608 --image ./data/kite.jpg
`
the value of bboxes is :
[array([0.00000000e+00, 0.00000000e+00, 1.35100000e+03, 8.99000000e+02,
       5.91896713e-01, 7.20000000e+01])]

, and it can't draw any boxes in the picture,

**Comment by sterlingrpi** [comment]
where did you get the pretrained weights?

**Comment by 2033329616** [comment]
Thanks, I got the wrong weight from other github link, when I use the weight in this github I can get the right results.
