### ISSUE TITLE
yolov4.weights to .pb? (not .tf)

### ISSUE THREAD

**Issue by chonyy** [hunglc007/tensorflow-yolov4-tflite#66]
Hi, I have read the README. It says that this project could convert yolov4 to .pb file.
I know I can run save_model.py to do that.
Can you give me the full command? 

It seems like this command will give me a .tf file, but I would want a .pb file.
`python save_model.py --weights ./data/yolov4.weights --output ./checkpoints/yolov4.tf --input_size 416 --model yolov4`

**Comment by jiejiangd** [comment]
Have you found a good way？
