### ISSUE TITLE
How to use pre-trained models to train your own dataset

### ISSUE THREAD

**Issue by zxj11838** [hunglc007/tensorflow-yolov4-tflite#72]
I use a pre-trained model，the following error occurs,  does anyone know how to solve it?

File "E:\PycharmProjects\objectDetection\yolo\yolov4\tensorflow-yolov4-tflite-master\core\utils.py", line 122, in load_weights
    assert len(wf.read()) == 0, 'failed to read all data'
AssertionError: failed to read all data

**Comment by in-die-nibelungen** [comment]
Check you specify an appropriate weight data to the model you're using. If no problem on it, would fail in downloading the weight data. For example, weight data for yolov4 is 257717640 bytes.
