### ISSUE TITLE
Tensorboard log and predicted images

### ISSUE THREAD

**Issue by MI-LA01** [hunglc007/tensorflow-yolov4-tflite#8]
Instead to only get the predicted images on the filesystem during the evaluation, this should be great to have the predictions *also* through Tensorboard, under the images/tab, no ? 

Easy fix : 
An images list []

and then something like  : 
```
with writer.as_default():
        images_2 = np.reshape(images[0:1000], (-1, 320, 320, 3))
        tf.summary.image("image data examples", images_2, max_outputs=1000, step=FLAGS.step)
```

Pb, keep track of the step : suggestion : pass as an external flag. 

If you wish I can prepare a PR for that.

**Comment by jzoker** [comment]
Hi @MI-LA01. Your idea is great. So yes, if you could make a contribution, feel free to do it. Thank you!
