### ISSUE TITLE
Reshape error when running save_model.py

### ISSUE THREAD

**Issue by mathiasjose** [hunglc007/tensorflow-yolov4-tflite#86]
```
Traceback (most recent call last):
  File "save_model.py", line 55, in <module>
    app.run(main)
  File "/home/ubuntu/.virtualenvs/tyt/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/ubuntu/.virtualenvs/tyt/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "save_model.py", line 51, in main
    save_tf()
  File "save_model.py", line 41, in save_tf
    utils.load_weights(model, FLAGS.weights)
  File "/home/ubuntu/tyt/core/utils.py", line 114, in load_weights
    conv_weights = conv_weights.reshape(conv_shape).transpose([2, 3, 1, 0])
ValueError: cannot reshape array of size 4619172 into shape (1024,512,3,3)
```

I am experiencing this issue when attempting to convert a Yolov4 model trained on custom classes to tf using save_model

Yolov3 works fine, however the Yolov4 model is more accurate.

**Comment by mathiasjose** [comment]
Solved! Just had to change coco.names in data
Thanks @hunglc007  for the work!!

**Comment by ejri** [comment]
Would please elaborate more on what changes you made? 

I've built a custom model, with a different number of classes. 
Where did you change the names from coco.names to the custom names, and number of classes from the default number to the custom number of classes?

**Comment by alphapibeta** [comment]
@ejri 
You need to go to 
```
path/tensorflow-yolov4-tflite/data/classes/coco.names  

```  
and change the classes according to your model
for example: if you have only two classes
```
person
tv

``` 
and the other way is to [change](https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/dafb42f3f2c4efacaa854613a4fe0300d39edcba/core/config.py#L14) to your classes.names

**Comment by ejri** [comment]
Yeah, ended up changing the coco.names to the custom list of classes

**Comment by mhcao916** [comment]
> @ejri
> You need to go to
> 
> ```
> path/tensorflow-yolov4-tflite/data/classes/coco.names  
> ```
> 
> and change the classes according to your model
> for example: if you have only two classes
> 
> ```
> person
> tv
> ```
> 
> and the other way is to [change](https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/dafb42f3f2c4efacaa854613a4fe0300d39edcba/core/config.py#L14) the line to your classes.names

it doesn't work, have you tried it?  anyway it will output this error!!

**Comment by ejri** [comment]
@mhcao916 I was working with yolo3 model. It kept giving me a lot of errors. I retrained on a yolo4 model, and it worked.

Don't know exactly what the issue was, but with yolo4, you need to change the names of classes as mentioned above.

go to 
`path/tensorflow-yolov4-tflite/data/classes/coco.names`

and change the classes according to your model
for example: if you have only two classes

```
person
tv
```

**Comment by cyberjam** [comment]
> @ejri
> 당신은 가야합니다
> 
> ```
> path/tensorflow-yolov4-tflite/data/classes/coco.names  
> ```
> 
> 
> 예를 들어 모델에 따라 클래스를 변경하십시오. 클래스 가 두 개 뿐인 경우
> 
> ```
> person
> tv
> ```
> 
> 다른 방법은 라인을 클래스 로 [변경](https://github.com/hunglc007/tensorflow-yolov4-tflite/blob/dafb42f3f2c4efacaa854613a4fe0300d39edcba/core/config.py#L14) 하는 것입니다.

Thx!!! so much! I owe u one!
