### ISSUE TITLE
coco_data_path

### ISSUE THREAD

**Issue by zcdliuwei** [hunglc007/tensorflow-yolov4-tflite#9]
# preprocess coco dataset
cd data
mkdir dataset
cd ..
cd scripts
python coco_convert.py --input COCO_ANOTATION_DATA_PATH --output val2017.pkl
python coco_annotation.py --coco_path COCO_DATA_PATH 
cd ..

so ,what is COCO_DATA_PATH, and where ?

**Comment by hunglc007** [comment]
if you run [script](https://github.com/pjreddie/darknet/blob/master/scripts/get_coco_dataset.sh), COCO_DATA_PATH is ./coco/
