### ISSUE TITLE
load weights error when to start train

### ISSUE THREAD

**Issue by netqyq** [hunglc007/tensorflow-yolov4-tflite#93]
AssertionError: failed to read all data

![image](https://user-images.githubusercontent.com/3492992/84721882-4e3fce80-afb4-11ea-98bd-11555952da55.png)

![image](https://user-images.githubusercontent.com/3492992/84721819-1f295d00-afb4-11ea-9b02-34686e2738db.png)

**Comment by remic33** [comment]
Same error here, seems that the change in classes number make it impossible to train with pretrain wiehgts.

**Comment by ponkotu-android** [comment]
It is because class number is different between built model and weight file.
The solution is to make weight file using below one.
https://github.com/AlexeyAB/darknet

The other is comment out the 'assert' line.
But I'm not sure it work well or not.

**Comment by netqyq** [comment]
@ponkotu-android you are right, because the weight file I specified was wrong. thank you.
