### ISSUE TITLE
.weights转tf时报错

### ISSUE THREAD

**Issue by myl353** [hunglc007/tensorflow-yolov4-tflite#94]
在运行save_model时报错：
2020-06-16 10:27:51.510005: W tensorflow/python/util/util.cc:319] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
WARNING:tensorflow:From /home/fwq/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
W0616 10:28:08.951637 139932055152384 deprecation.py:506] From /home/fwq/anaconda3/lib/python3.6/site-packages/tensorflow_core/python/ops/resource_variable_ops.py:1786: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: yolov4.tf/assets
I0616 10:28:14.113117 139932055152384 builder_impl.py:775] Assets written to: yolov4.tf/assets

模型无法保存出来，请问需要怎么修改？

**Comment by maobj** [comment]
你好，我也碰到了类似的问题，请问您后来是怎么解决的？

**Comment by myl980** [comment]
没有解决，我换了D版的模型来转



---原始邮件---
发件人: "maobj"<notifications@github.com&gt;
发送时间: 2020年10月20日(周二) 晚上8:23
收件人: "hunglc007/tensorflow-yolov4-tflite"<tensorflow-yolov4-tflite@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"myl353"<980477635@qq.com&gt;;
主题: Re: [hunglc007/tensorflow-yolov4-tflite] .weights转tf时报错 (#94)




 
你好，我也碰到了类似的问题，请问您后来是怎么解决的？

**Comment by maobj** [comment]
请问D版模型是什么意思？低版嘛？我现在有个darknet转pb和tflite的需求，求指个路哪个版本能转成，多谢了



binjiemao@126.com
 
发件人： myl353
发送时间： 2020-10-20 20:25
收件人： hunglc007/tensorflow-yolov4-tflite
抄送： maobj; Comment
主题： Re: [hunglc007/tensorflow-yolov4-tflite] .weights转tf时报错 (#94)
没有解决，我换了D版的模型来转 



---原始邮件--- 
发件人: "maobj"<notifications@github.com&gt; 
发送时间: 2020年10月20日(周二) 晚上8:23 
收件人: "hunglc007/tensorflow-yolov4-tflite"<tensorflow-yolov4-tflite@noreply.github.com&gt;; 
抄送: "State change"<state_change@noreply.github.com&gt;;"myl353"<980477635@qq.com&gt;; 
主题: Re: [hunglc007/tensorflow-yolov4-tflite] .weights转tf时报错 (#94) 





你好，我也碰到了类似的问题，请问您后来是怎么解决的？
