### ISSUE TITLE
CANCEL % of estimation on BBOX ??

### ISSUE THREAD

**Issue by erolgerceker** [hunglc007/tensorflow-yolov4-tflite#98]
how can i cancel/deactivate the "bbox % of estimation" . i dont wanna see on the bbox

**Comment by GREAT0** [comment]
> how can i cancel/deactivate the "bbox % of estimation" . i dont wanna see on the bbox

Were you able to find a solution to this? Removal of the percentage score in BBox?

**Comment by erolgerceker** [comment]
i did it
